version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming your Dockerfile is in the same directory
    ports:
      - "8080:8080"  # Expose port 8080 for your Spring Boot app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgrespassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres-db
    networks:
      - app-network

  postgres-db:
    image: postgres:17  # Use the official PostgreSQL image
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data across container restarts
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
