services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:8080" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/utilisateur
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres-db
    networks:
      - app-network

  postgres-db:
    image: postgres:17 
    environment:
      POSTGRES_DB: utilisateur
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
